---
# tasks file for roles/win_ad_install

- name: Install AD-Domain-Services      
 
  win_feature:
  
        name: AD-Domain-Services
        state: present
  tags:
    - services
 
- name: Setup AD Domain 
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
    register: active_directory_controllers

- name: reboot once DC created

  win_reboot:
      when: active_directory_controllers.reboot_required

- name: List DCs in domain
  win_shell: "nltest /dclist:{{ ad_domain_name }}"
  register: domain_list

- debug:
       var: domain_list
